### ISSUE TITLE
Site: Improve Navigation Visibility

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/LunarSparkle2403A#6]
- [x] Improve the visibility of the navigation links on all three pages

This site has a navigation bar near the top of each page, with links for all three pages. Can anything be done to improve the visibility of these hyperlinks? 

Some ideas: 
- Larger/bolder font
- Better color contrast
- Indicate which page the user is on (see below)

To indicate which page the user is currently on, follow these steps: 

1. Open one of the HTML pages and locate the navigation menu code. 
2. In the opening anchor tag of the menu item for that same page, add id='current' (after the HREF attribute) 
    (Leave the other two menu items alone)
4. Repeat for the other two pages, adjusting only the menu item for _that page_ 
5. In style.css, add the following style: **nav ul li a#current**
    (it's a good idea to place this immediately below nav ul li a)
6. Add styles to make this menu item appear different from the other menu items (such as a font color or background color difference)
7. Test and observe the results

**Comment by bufnjon** [comment]
fixes are in,having issues doing commit

**Comment by PatrickFrankAIU** [comment]
@bufnjon Vickie when you get a chance a screenshot or a list of the errors would help. We'll take a look at it tonight during class.

**Comment by bufnjon** [comment]
![vscode](https://github.com/PatrickFrankAIU/LunarSparkle2403A/assets/88343637/7e32723c-59c2-4ab2-a0ca-8742d2743881)


Ive got all these extra files. I did close the file and the only way I could remember to get them back was to clone the repository so possibly it brought in extra changes from others. No error, the commit just keeps spinning.

**Comment by PatrickFrankAIU** [comment]
@bufnjon Vickie, if you have time before class, make note of all of your changes. It's likely that you'll have to clone the repo again and then apply your changes to the new copy. (You don't have to delete your existing copy of the repo to do this, so it should be fairly easy to copy your changes into the new clone.)

**Comment by bufnjon** [comment]
ok I'll hop on a little early!

**Comment by PatrickFrankAIU** [comment]
Also, you can try this if you want, but you should collect your changes elsewhere first. What this is SUPPOSED to do is pull the latest copy and then apply *your* changes on top of it. Then you have to sync again. 

![image](https://github.com/PatrickFrankAIU/LunarSparkle2403A/assets/134087916/3aa43f72-e358-49f0-9066-b7e423879902)
